[plugin]
repository = "https://github.com/Seventhxiv/Collections.git"
commit = "c6a62ea3bc4298640689925de07be48014204536"
owners = ["Seventhxiv"]
project_path = "Collections"
changelog = """
Collections v1.0.2.1
- Update to API 11
- Fix preview bugs
"""