[plugin]
repository = "https://github.com/Seventhxiv/Collections.git"
commit = "ee5fc5e4d91934cafd6aa5523ea9da9ad7984af3"
owners = ["Seventhxiv"]
project_path = "Collections"
changelog = """
Collections v1.0.1.3
- Prevent some crashes by changing cache Dictionaries to Concurrent
"""