[plugin]
repository = "https://github.com/Seventhxiv/Collections.git"
commit = "d76ca9b6f1128e8a44df8009e77292605df1d083"
owners = ["Seventhxiv"]
project_path = "Collections"
changelog = """
Collections v1.0.1.4
- Refactoring code
"""