[plugin]
repository = "https://github.com/Seventhxiv/Collections.git"
commit = "2d1d7bd38b0efb62c1a183a2ce88890c7c7cdf48"
owners = ["Seventhxiv"]
project_path = "Collections"
changelog = """
Collections v1.0.1.1
- Mounts/Minions can now be summoned from the collection UI
- Clicking on Duty sources now open the duty window
- New feature: Copy Examine glamour
- New feature: Copy glamour set to Plate
- New feature: Favorite list
- New feature: Wish list
- A bunch of Data improvements (NPC locations, updated items to shops/instances)
- Configuration now actually saves plugin state
- Cache layer for Excel and Collectibles
- Redone the Dresser observer to be more straightforward
- Changed logs to Information level
"""