[plugin]
repository = "https://github.com/Seventhxiv/Collections.git"
commit = "256daf1418c855880ea586f4096d7bc3467f7f09"
owners = ["Seventhxiv"]
project_path = "Collections"
changelog = """
Collections v1.0.2.1
- Update to API 11
- Fix preview bugs
"""