[plugin]
repository = "https://github.com/Seventhxiv/Collections.git"
commit = "7b7b4ba819c019c03c3182cda103b725792a5bbb"
owners = ["Seventhxiv"]
project_path = "Collections"
changelog = """
Collections v1.0.1.4
- Refactoring code
"""